"""rename user source to human

Revision ID: d4049905e648
Revises: e36f2540d5c1
Create Date: 2026-05-10 14:15:50.821591

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4049905e648"
down_revision: str | Sequence[str] | None = "e36f2540d5c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_documents_current_version_id"), "documents", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "documents",
        "document_versions",
        ["current_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###

    # Custom: Rename enum values
    op.execute("ALTER TYPE eversionsource RENAME VALUE 'USER' TO 'human'")
    op.execute("ALTER TYPE eversionsource RENAME VALUE 'AI' TO 'ai'")


def downgrade() -> None:
    """Downgrade schema."""
    # Custom: Revert enum values
    op.execute("ALTER TYPE eversionsource RENAME VALUE 'human' TO 'USER'")
    op.execute("ALTER TYPE eversionsource RENAME VALUE 'ai' TO 'AI'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_documents_current_version_id"),
        "documents",
        "document_versions",
        ["current_version_id"],
        ["id"],
    )
    # ### end Alembic commands ###
